name: JustHomes
version: 1.14.4
description: homes
api-version: 1.14
author: Kondee
main: me.kondi.Homes.Main
commands:
  jsethome:
    description: You can create homes with it.
    usage: /<command> <homename>
    aliases: js
  jhome:
    description: Teleports you to your home.
    usage: /<command> <homename>
    aliases: jh
  jlisthome:
    description: lists all your homes.
    usage: /<command>
    aliases: jl
  jdelhome:
    description: Deletes your home.
    usage: /<command> <homename>
    aliases: jd